version: 0.2
env:
  variables:
    S3_BUCKET_NAME: "dataclass-tool-lambda-s3bucket-7mc6wggd07uu"

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd frontend
      - echo $S3_BUCKET_NAME
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
     commands:
      - aws s3 sync build/ s3://${S3_BUCKET_NAME}
      - echo Build completed on `date`
#      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"

artifacts:
  files:
      - '**/*'
  discard-paths: yes